In [1]:
import numpy as np # linear algebra
import pandas as pd
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv") 
movies = movies.merge(credits,on='title')
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
movies.dropna(inplace=True)
movies.isnull().sum()
movies.iloc[0].genres
import ast

def convert(obj):
    L = []
   
    if isinstance(obj, list):
        return obj
    
    
    if isinstance(obj, str):
        try:
            items = ast.literal_eval(obj)
            if isinstance(items, list):
                for i in items:
                    if isinstance(i, dict) and 'name' in i:
                        L.append(i['name'])
        except (ValueError, SyntaxError):
            pass
            
    return L
movies.dropna(inplace=True)    
movies["genres"]=movies["genres"].apply(convert)   
movies["keywords"]=movies["keywords"].apply(convert)
import ast

def convert(obj):
    L = []
   
    if isinstance(obj, list):
        return obj
    
    
    if isinstance(obj, str):
        try:
            items = ast.literal_eval(obj)
            if isinstance(items, list):
                for i in items:
                    if isinstance(i, dict) and 'name' in i:
                        L.append(i['name'])
        except (ValueError, SyntaxError):
            pass
            
    return L
movies.dropna(inplace=True)    
movies["genres"]=movies["genres"].apply(convert)   
movies["keywords"]=movies["keywords"].apply(convert) 
import ast

def convert3(text):
    
    if isinstance(text, list):
        return text[:3]
    
    if not isinstance(text, str):
        return []
    
    L = []
    try:
        items = ast.literal_eval(text)
        if isinstance(items, list):
            for i in items[:3]:  
                if isinstance(i, dict) and 'name' in i:
                    L.append(i['name'])
    except (ValueError, SyntaxError):
        return []
        
    return L
movies["cast"]=movies["cast"].apply(convert3)  
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
import ast

def fetch_director(text):
    # Handle case where the column was already converted to a list
    if isinstance(text, list):
        return text
    
    # Handle missing/non-string values
    if not isinstance(text, str):
        return []
    
    L = []
    try:
        items = ast.literal_eval(text)
        if isinstance(items, list):
            for i in items:
                if isinstance(i, dict) and i.get('job') == 'Director':
                    L.append(i.get('name'))
    except (ValueError, SyntaxError):
        return []
        
    return L
movies["crew"]=movies["crew"].apply(fetch_director) 
movies.head()
movies["overview"]=movies["overview"].apply(lambda x:x.split())

In [15]:
movies.head()
movies["tags"]= movies["overview"]+movies["genres"]+movies["keywords"]+movies["cast"]+movies["crew"]
movies=movies.drop(columns=["overview","genres","keywords","cast","crew"])

In [17]:
movies.head()
movies["tags"]=movies["tags"].apply(lambda x:" ".join(x))

In [18]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [22]:
new=movies.copy()
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(new['tags']).toarray()
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
new[new['title'] == 'The Lego Movie'].index[0]
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [26]:
recommend('Ghost')

You, Me and Dupree
I Am Sam
Ca$h
Nowhere to Run
Farce of the Penguins

In [28]:
import pickle

# 1. Export the Dataframe
# We convert it to a dictionary first to avoid pandas version mismatch errors in the backend
pickle.dump(new.to_dict(), open('movie_dict.pkl', 'wb'))

# 2. Export the Similarity Matrix
# Replace 'similarity' with whatever variable name you used for your matrix
pickle.dump(similarity, open('similarity.pkl', 'wb'))

print("Model and Dataframe successfully exported!")

Model and Dataframe successfully exported!